import swaggerAutogen from 'swagger-autogen';

// Schemas generated by prisma and validators

import { PostSchemas } from '../validators/post.validators';
import * as prismaSchemas from './json-schema.json';

const doc = {
  info: {
    title: 'REST Api Documentation',
    description: 'REST Api Documentation',
    version: '1.0.0'
  },
  tags: [
    {
      name: 'Posts',
      description: 'Posts related end-points'
    }
  ],
  components: {
    '@schemas': {
      ...prismaSchemas.definitions,
      ...PostSchemas
    }
  },
  host: 'localhost:8000'
};

const outputFile = './openapi.json';
const routes = ['./src/app.ts'];

// Meant to be used with `npm run swagger`

void swaggerAutogen({ openapi: '3.0.0' })(outputFile, routes, doc);
