services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: server
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}
